main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('albums/', views.albums_index, name='index'),
    path('albums/<int:album_id>/', views.albums_detail, name='detail'),
    path('albums/create/', views.AlbumCreate.as_view(), name='albums_create'),
    path('albums/<int:pk>/update', views.AlbumUpdate.as_view(), name='albums_update'),
    path('albums/<int:pk>/delete', views.AlbumDelete.as_view(), name='albums_delete'),
    path('albums/<int:album_id>/add_listening/', views.add_listening, name='add_listening'),
    path('formats/', views.FormatList.as_view(), name='formats_index'),
    path('formats/<int:pk>/', views.FormatDetail.as_view(), name='formats_detail'),
    path('formats/create/', views.FormatCreate.as_view(), name='formats_create'),
    path('formats/<int:pk>/update/', views.FormatUpdate.as_view(), name='formats_update'),
    path('formats/<int:pk>/delete/', views.FormatDelete.as_view(), name='formats_delete'),
    path('albums/<int:album_id>/assoc_format/<int:format_id>/', views.assoc_format, name='assoc_format'),
]

thesourcecollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date

# Create your models here.
LISTEN = (
    ('M', 'Melvin'),
    ('I', 'Info'),
    ('O', 'Osario')
)

class Format(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('formats_detail', kwargs={'pk': self.id})

class Album(models.Model):
    title = models.CharField(max_length=100)
    artist = models.CharField(max_length=100)
    label = models.CharField(max_length=100)
    release = models.IntegerField()
    formats = models.ManyToManyField(Format)
    

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail', kwargs={'album_id': self.id})

class Listening(models.Model):
    date = models.DateField('listening date')
    listen = models.CharField(
        max_length=1,
        choices=LISTEN,
        default=LISTEN[0][0]
        )
    
    album = models.ForeignKey(Album, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_listen_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from.models import Listening

class ListeningForm(ModelForm):
    class Meta:
        model = Listening
        fields = ['date', 'listen']

main_app/views.py
from http.client import TOO_MANY_REQUESTS
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Album, Format
from .forms import ListeningForm

    # Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def albums_index(request):
    albums = Album.objects.all()
    return render(request, 'albums/index.html', {'albums': albums})

def albums_detail(request, album_id):
    album = Album.objects.get(id=album_id)
    id_list = album.formats.all().values_list('id')
    formats_album_doesnt_have = Format.objects.exclude(id__in=id_list)
    listening_form = ListeningForm()
    return render(request, 'albums/detail.html', {
        'album': album, 
        'listening_form': listening_form, 
        'formats': formats_album_doesnt_have
    })

def assoc_format(request, album_id, format_id):
    Album.objects.get(id=album_id).formats.add(format_id)
    return redirect('detail', album_id=album_id)

class AlbumCreate(CreateView):
    model = Album
    fields = ['title', 'artist', 'label', 'release']

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['label', 'release']

class AlbumDelete(DeleteView):
    model = Album
    success_url = '/albums/'

def add_listening(request, album_id):
  form = ListeningForm(request.POST)
  if form.is_valid():
      new_listening = form.save(commit=False)
      new_listening.album_id = album_id
      new_listening.save()
  return redirect('detail', album_id=album_id)

class FormatList(ListView):
    model = Format

class FormatDetail(DetailView):
    model = Format

class FormatCreate(CreateView):
    model = Format
    fields = '__all__'

class FormatUpdate(UpdateView):
    model = Format
    fields = ['name']

class FormatDelete(DeleteView):
    model = Format
    success_url = '/formats/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About The Source Collector</h1>
<hr />
<p>Hire A Source Collector!</p>

{% endblock %}

main_app/templates/albums/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Album Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ album.title }}</span>
        <p>Artist: {{ album.artist }}</p>
        <p>Label: {{ album.label}}</p>
          <p>Release: {{ album.release }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'albums_update' album.id %}">Edit</a>
        <a href="{% url 'albums_delete' album.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_listening' album.id %}" method="POST">
        {% csrf_token %}
        {{ listening_form.as_p }}
        <input type="submit" class="btn" value="Add Listening">
      </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Listening</th></tr>
      </thead>
      <tbody>
        {% for listening in album.listening_set.all %}
          <tr>
            <td>{{listening.date}}</td>
            <td>{{listening.get_listen_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ album.title }} Format</h3>
    {% if album.formats.count %}
      {% for format in album.formats.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
               {{ format.name }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Formats :(</h5>
    {% endif %}
  </div>
  <!-- Available format will come after this line -->
  <div class="col s6">
    <h3>Available Format</h3>
    {% if formats.count %}
      {% for format in formats.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
             {{ format.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_format' album.id format.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{cat.name}} Already Has All Formats Available</h5>
    {% endif %}
  </div>
</div>
<script>

    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });

    const selectEl = document.getElementById('id_listen');
    M.FormSelect.init(selectEl)
</script>

{% endblock %}

main_app/templates/albums/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Album List</h1>

{% for album in albums %}
<div class="card">
  <a href="{% url 'detail' album.id %}"">
  <div class="card-content">
      <span class="card-title">{{ album.title }}</span>
      <p>Artist: {{ album.artist }}</p>
      <p>Label: {{ album.label }}</p>
      <p>Release: {{ album.release }}</p>
    </div>
   </a>
</div>
{% endfor %}

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>The Source Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %} class="left brand-logo">&nbsp;&nbsp;The Source Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'formats_create' %}">Add a Format</a></li>
          <li><a href="{% url 'formats_index' %}">View All The Formats</a></li>
          <li><a href="{% url 'albums_create' %}">Add an Album</a></li>
          <li><a href="{% url 'index' %}">View All The Albums</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2022 The Source Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/album_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Album</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' album.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/album_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Album</h1>
  {% endif %}
  <form action="" method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Add Album!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/format_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Format</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'formats_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/format_detail.html
{% block content %}

<h1>Format Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ format.name }}</span>
      </div>
      <div class="card-action">
        <a href="{% url 'formats_update' format.id %}">Edit</a>
        <a href="{% url 'formats_delete' format.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/format_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Format</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/format_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Format List</h1>

{% for format in format_list %}
  <a href="{% url 'formats_detail' format.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ format.name }}</span>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}